BDD_NAME:like-it-pre-prod
BDD_PASSWORD: 12345678910 
BDD_USER: coak
MINIO_ACCESS_KEY: coak
MINIO_SECRET_KEY: 123456789
RASPBERRY_HOST: ssh.coak.fr
RASPBERRY_SSH_KEY:
RASPBERRY_USER: user
SECRET_KEY: mysupersecret